language: en-US
early_access: false

reviews:
  profile: chill
  request_changes_workflow: false
  fail_commit_status: false

  high_level_summary: true
  high_level_summary_in_walkthrough: true
  collapse_walkthrough: true
  poem: false
  in_progress_fortune: false
  sequence_diagrams: false
  suggested_labels: false
  suggested_reviewers: false

  auto_review:
    enabled: true
    drafts: false
    base_branches: [".*"]
    auto_incremental_review: true
    auto_pause_after_reviewed_commits: 0

knowledge_base:
  code_guidelines:
    enabled: true
    filePatterns:
      - "REVIEW_GUIDELINES.md"
